import type { Metadata } from "next";
import "./globals.css";
import Navegacao from "@/components/etapa-a-tradicional/Navegacao/Navegacao";

export const metadata: Metadata = {
  title: "TCC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Navegacao />
        {children}
      </body>
    </html>
  );
}
